docker run -it `
	-e POSTGRES_USER="root" `
	-e POSTGRES_PASSWORD="root" `
	-e POSTGRES_DB="ny_taxi" `
	-v ${PWD}/postgres_data:/var/lib/postgresql/data `
	-p 5432:5432 `
	--network pg-network `
	--name pg-database `
	postgres:latest

docker run -it `
	-e PGADMIN_DEFAULT_EMAIL='root@root.com' `
	-e PGADMIN_DEFAULT_PASSWORD='root' `
	-p 8080:80 `
	--network pg-network `
	--name pg-admin `
	-d dpage/pgadmin4

python upload_data.py `
	--user=root `
	--password=root `
	--host=localhost `
	--port=5432 `
	--db=ny_taxi `
	--table=ny_taxi_data `
	--csv_url=https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz

docker build -t ny_taxi_upload:v1 .

docker run -it `
	--network=pg-network `
	--name=pg-upload `
	ny_taxi_upload:v2 `
		--user=root `
		--password=root `
		--host=pg-database `
		--port=5432 `
		--db=ny_taxi `
		--table=ny_taxi_data `
		--csv_url=https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz

docker build -t ny_taxi_upload:v2 .

docker run -it `
	--network=pg-network `
	--name=pg-upload `
	ny_taxi_upload:v2 `
		--host=pg-database `
		--period=2025-02

---The compose docker was not connected to the network, so I need to connect pg-databse manually
---before excecute pg-upload
docker network connect pg-network pg-database
---Fix this later